### ISSUE TITLE
Cannot restart a node alone if the cluster crashed

### ISSUE THREAD

**Issue by turtleDeng** [emqtt/emq-relx#11]
Steps:

1. Start emqttd1@127.0.0.1
2. Start emqttd2@127.0.0.1
3. cd emqttd2  && ./bin/emqttd_ctl cluster join emqttd1@127.0.0.1
4. Stop emqttd1@127.0.0.1
5. Stop emqttd2@127.0.0.1
6. Failed to start emqttd2@127.0.0.1 alone

**Comment by emqplus** [comment]
Fixed in 2.0.1
