### ISSUE TITLE
Unable to compile (make / make rel) on OSX El-Capitan

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emq-relx#117]
Erlang OTP: 19.3

getting this error when running "**make**":
```
make[2]: Nothing to be done for `all'.
mix local.hex --force
make[1]: mix: No such file or directory
make[1]: *** [all] Error 1
make: *** [deps] Error 2
```

getting this when running "**make rel**"
```
===> Application metadata exists but version is not available: /Users/liam/Documents/dev/myapp/erlang/emq-relx/deps/emq_elixir_plugin/elixir/lib/mix/test/fixtures/archive
```

**Comment by grutabow** [comment]
Please delete deps/emq_elixir_plugin directory and try again.

If there are errors either, please post more logs of 'make'.

**Comment by sohailgerman92** [comment]
@syberkitten Hi !! I too had the same problem just use

>  `brew install elixir`

 as the elixir lib is not installed in your system and due to App Store application validation, emq_elixir_plugin doesn't gets to help you with elixir plugin.

I hope that helps, if not please feel happy to contact me.

**Comment by syberkitten** [comment]
Now getting this error:

`
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/liam/Documents/dev/roboteam/erlang/emq-relx/deps
          /Users/liam/Documents/dev/kerl/19.3/lib
          /Users/liam/Documents/dev/roboteam/erlang/emq-relx/apps
===> Failed to solve release:
 Dependency ekka is specified as a dependency but is not reachable by the system.
`

**Comment by syberkitten** [comment]
I'm getting this long error as well, before the Ekka fails.

`

15:49:23.106 [error] Failed updating session:
   ProfileName: :httpc_mix
   SessionId:   {{'repo.hex.pm', 443}, #PID<0.91.0>}
   Pos:         7
   Value:       0
when
   Session (db) info: :undefined
   Session (db):      {:session, {{'repo.hex.pm', 443}, #PID<0.91.0>}, false, :https,
 {:sslsocket, {:gen_tcp, #Port<0.9597>, :tls_connection, :undefined},
  #PID<0.92.0>}, {:essl, []}, 1, :keep_alive, true}
   Session (record):  {:EXIT,
 {:badarg,
  [{:ets, :lookup,
    [:httpc_mix__session_db, {{'repo.hex.pm', 443}, #PID<0.91.0>}], []},
   {:httpc_manager, :lookup_session, 2, [file: 'httpc_manager.erl', line: 189]},
   {:httpc_handler, :update_session, 4,
    [file: 'httpc_handler.erl', line: 1909]},
   {:httpc_handler, :handle_empty_queue, 4,
    [file: 'httpc_handler.erl', line: 1368]},
   {:httpc_handler, :handle_info, 2, [file: 'httpc_handler.erl', line: 471]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 615]},
   {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 681]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
   T: :error
   E: :badarg

15:49:23.107 [error] Failed updating session:
   ProfileName: :httpc_mix
   SessionId:   {{'repo.hex.pm', 443}, #PID<0.91.0>}
   Pos:         9
   Value:       true
when
   Session (db) info: :undefined
   Session (db):      {:session, {{'repo.hex.pm', 443}, #PID<0.91.0>}, false, :https,
 {:sslsocket, {:gen_tcp, #Port<0.9597>, :tls_connection, :undefined},
  #PID<0.92.0>}, {:essl, []}, 1, :keep_alive, false}
   Session (record):  {:EXIT,
 {:badarg,
  [{:ets, :lookup,
    [:httpc_mix__session_db, {{'repo.hex.pm', 443}, #PID<0.91.0>}], []},
   {:httpc_manager, :lookup_session, 2, [file: 'httpc_manager.erl', line: 189]},
   {:httpc_handler, :update_session, 4,
    [file: 'httpc_handler.erl', line: 1909]},
   {:httpc_handler, :maybe_make_session_available, 2,
    [file: 'httpc_handler.erl', line: 1516]},
   {:httpc_handler, :answer_request, 3,
    [file: 'httpc_handler.erl', line: 1507]},
   {:httpc_handler, :terminate, 2, [file: 'httpc_handler.erl', line: 759]},
   {:gen_server, :try_terminate, 3, [file: 'gen_server.erl', line: 643]},
   {:gen_server, :terminate, 7, [file: 'gen_server.erl', line: 809]}]}}
   T: :error
   E: :badarg

15:49:23.119 [error] GenServer #PID<0.91.0> terminating
** (stop) {:failed_updating_session, [profile: :httpc_mix, session_id: {{'repo.hex.pm', 443}, #PID<0.91.0>}, pos: 9, value: true, etype: :error, error: :badarg, stacktrace: [{:ets, :update_element, [:httpc_mix__session_db, {{'repo.hex.pm', 443}, #PID<0.91.0>}, {9, true}], []}, {:httpc_manager, :update_session, 4, [file: 'httpc_manager.erl', line: 210]}, {:httpc_handler, :update_session, 4, [file: 'httpc_handler.erl', line: 1887]}, {:httpc_handler, :maybe_make_session_available, 2, [file: 'httpc_handler.erl', line: 1516]}, {:httpc_handler, :answer_request, 3, [file: 'httpc_handler.erl', line: 1507]}, {:httpc_handler, :terminate, 2, [file: 'httpc_handler.erl', line: 759]}, {:gen_server, :try_terminate, 3, [file: 'gen_server.erl', line: 643]}, {:gen_server, :terminate, 7, [file: 'gen_server.erl', line: 809]}]]}
    (inets) httpc_handler.erl:1911: :httpc_handler.update_session/4
    (inets) httpc_handler.erl:1516: :httpc_handler.maybe_make_session_available/2
    (inets) httpc_handler.erl:1507: :httpc_handler.answer_request/3
    (inets) httpc_handler.erl:759: :httpc_handler.terminate/2
    (stdlib) gen_server.erl:643: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:809: :gen_server.terminate/7
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.9597>, :tls_connection, :undefined}, #PID<0.92.0>}, "HTTP/1.1 200 OK\r\nx-amz-id-2: FG4cKpK0Rs1/I4zvXlaLldsJTUlYK6Bi6r03irekWQJUlyHyMe2wTFKEIq2/IPgYO3F6nqqoVDE=\r\nx-amz-request-id: 80922D054E964B00\r\nx-amz-replication-status: COMPLETED\r\nLast-Modified: Tue, 29 Aug 2017 17:21:23 GMT\r\nETag: \"111ebb23c90fa55e3ac4562a3e0212a9\"\r\nCache-Control: public, max-age=604800\r\nx-amz-meta-surrogate-key: installs\r\nx-amz-version-id: uI44.m_ssUM8J8Jcp8ITsfTM9fHkcADn\r\nContent-Type: binary/octet-stream\r\nServer: AmazonS3\r\nContent-Length: 350\r\nAccept-Ranges: bytes\r\nDate: Sun, 01 Oct 2017 12:49:23 GMT\r\nVia: 1.1 varnish\r\nAge: 415435\r\nConnection: keep-alive\r\nX-Served-By: cache-hhn1523-HHN\r\nX-Cache: HIT\r\nX-Cache-Hits: 1\r\nX-Timer: S1506862163.023254,VS0,VE7\r\n\r\npZEVW1WbfWIz87d4ZqplFHboMbI5Z/7RyBVUMQ8HKYtwPp0jo61CXPmuKMF5Ab1c\nZONuHkSM14rS5u1ZsFOJhdBPkBsFkb/ttTlSXSizx98BrRCrjy54HAl7Z/1KbZN9\n9WK0HCZIMDZ27Pa+F5IDqeNysJsk1js9qZRQMqllPdF1cays86qU1zLbWio9iWY6\nKoi1QajqWcdVURv5cmnluZHCyKJ452Q/TPLgE7eQ42YLcdRSFy61sM+Zkf1Fpbkk\nRBsoJCnE5f/F50nvQH8GeZTPE2XXzanjuNsG9VAseV+LlDVcpQh/Dwx/+uObBbYD\nJIats4UxWsP8vCRBMJ4jOg==\n"}
State: {:state, {:request, #Reference<0.0.3.24>, #PID<0.46.0>, 0, :https, {'repo.hex.pm', 443}, '/installs/hex-1.x.csv.signed', [], :get, {:http_request_h, :undefined, 'keep-alive', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'repo.hex.pm', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], 'Mix/1.5.0-dev', :undefined, :undefined, :undefined, '0', :undefined, :undefined, :undefined, :undefined, :undefined, ...}, {[], []}, {:http_options, 'HTTP/1.1', :infinity, true, {:essl, []}, :undefined, true, :infinity, false}, 'https://repo.hex.pm/installs/hex-1.x.csv.signed', [], :none, [], 1506862162679, :undefined, :undefined, false}, {:session, {{'repo.hex.pm', 443}, #PID<0.91.0>}, false, :https, {:sslsocket, {:gen_tcp, #Port<0.9597>, :tls_connection, :undefined}, #PID<0.92.0>}, {:essl, []}, 1, :keep_alive, false}, :undefined, :undefined, :undefined, {:httpc_response, :parse, [:nolimit, true]}, {[], []}, {[], []}, :new, [], :nolimit, :nolimit, {:options, {:undefined, []}, {:undefined, []}, 0, 2, 5, 120000, 2, :disabled, false, :inet, :default, :default, []}, {:timers, [], :undefined}, :httpc_mix, :inactive}


`

**Comment by syberkitten** [comment]
finally managed to compile, 2.3.0
