### ISSUE TITLE
Cannot load any plugin

### ISSUE THREAD

**Issue by hamdijmii1992** [emqtt/emq-relx#137]
Here is my log file content after starting the server:

> starting emqttd on node 'emq@127.0.0.1'
> emqttd ctl is starting...[ok]
> emqttd hook is starting...[ok]
> emqttd router is starting...[ok]
> emqttd pubsub is starting...[ok]
> emqttd stats is starting...[ok]
> emqttd metrics is starting...[ok]
> emqttd pooler is starting...[ok]
> emqttd trace is starting...[ok]
> emqttd client manager is starting...[ok]
> emqttd session manager is starting...[ok]
> emqttd session supervisor is starting...[ok]
> emqttd wsclient supervisor is starting...[ok]
> emqttd broker is starting...[ok]
> emqttd alarm is starting...[ok]
> emqttd mod supervisor is starting...[ok]
> emqttd bridge supervisor is starting...[ok]
> emqttd access control is starting...[ok]
> emqttd system monitor is starting...[ok]
> emqttd 2.3 is running now
> Eshell V8.3  (abort with ^G)
> (emq@127.0.0.1)1> 05:07:35.219 [error] Autocluster exception: {badmatch,undefined}
> 

I cannot understand why I had this error, but my real problem now is that I cannot load any plugin.
When I tried to load such a plugin I got this error as follows:

> ./emqttd_ctl plugins load emq_auth_clientid
> Reason:{badmatch,undefined}, get_stacktrace:[{emqttd_plugins,plugin,1,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,116}]},
>                                              {emqttd_plugins,
>                                               '-list/0-lc$^0/1-0-',1,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,102}]},
>                                              {emqttd_plugins,
>                                               '-list/0-lc$^0/1-0-',1,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,102}]},
>                                              {emqttd_plugins,list,0,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,102}]},
>                                              {emqttd_plugins,find_plugin,1,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,169}]},
>                                              {emqttd_plugins,load,1,
>                                               [{file,"src/emqttd_plugins.erl"},
>                                                {line,129}]},
>                                              {emqttd_cli,plugins,1,
>                                               [{file,"src/emqttd_cli.erl"},
>                                                {line,302}]},
>                                              {emqttd_ctl,run,1,
>                                               [{file,"src/emqttd_ctl.erl"},
>                                                {line,83}]}]
> RPC to emq@127.0.0.1 error: {badmatch,undefined}

**Comment by emqplus** [comment]
@hamdijmii1992 Do you configure the autocluster strategy?  

```
cluster.discovery = manual
```

**Comment by mingchuno** [comment]
@emqplus I have the same issue and I have set `cluster.discovery = manual`
