### ISSUE TITLE
Emq Not starting following occurs when server starts

### ISSUE THREAD

**Issue by sohailgerman92** [emqtt/emq-relx#138]
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
{error,{bad_return,{{emqttd_app,start,[normal,[]]},
                    {'EXIT',{{badmatch,undefined},
                             [{emqttd_plugins,plugin,1,
                                              [{file,"src/emqttd_plugins.erl"},{line,116}]},
                              {emqttd_plugins,'-list/0-lc$^0/1-0-',1,
                                              [{file,"src/emqttd_plugins.erl"},{line,102}]},
                              {emqttd_plugins,'-list/0-lc$^0/1-0-',1,
                                              [{file,"src/emqttd_plugins.erl"},{line,102}]},
                              {emqttd_plugins,list,0,
                                              [{file,"src/emqttd_plugins.erl"},{line,102}]},
                              {emqttd_plugins,load_plugins,2,
                                              [{file,"src/emqttd_plugins.erl"},{line,74}]},
                              {emqttd_app,start,2,[{file,"src/emqttd_app.erl"},{line,49}]},
                              {application_master,start_it_old,4,
                                                  [{file,"application_master.erl"},{line,273}]}]}}}}}
(emqttd@20.0.5.88)4> 
07:16:59.036 [info]  Application emqttd exited: exited in: :emqttd_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :undefined
            (emqttd) src/emqttd_plugins.erl:116: :emqttd_plugins.plugin/1
            (emqttd) src/emqttd_plugins.erl:102: :emqttd_plugins."-list/0-lc$^0/1-0-"/1
            (emqttd) src/emqttd_plugins.erl:102: :emqttd_plugins."-list/0-lc$^0/1-0-"/1
            (emqttd) src/emqttd_plugins.erl:102: :emqttd_plugins.list/0
            (emqttd) src/emqttd_plugins.erl:74: :emqttd_plugins.load_plugins/2
            (emqttd) src/emqttd_app.erl:49: :emqttd_app.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
07:16:59.033 [error] CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: no match of right hand value undefined in emqttd_plugins:plugin/1 line 116 in application_master:init/4 line 134

**Comment by emqplus** [comment]
Invalid issue, closed.
