### ISSUE TITLE
emqttd_ctl script does not support node cookies with '=' characters

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqtt/emq-relx#144]
For example if I have a following configuration in the etc/emq.conf:
  node.cookie = 'd!C!v-p_XNSAIv5eIcXyLH%5gv4e=QFkjsf$p>8j@DC;?r[jy%7eH%TZUk^Qci-s'

It would not work if I ran './bin/emqttd_ctl clients list':
  Node 'emqttd@127.0.0.1' not responding to pings.

https://github.com/emqtt/emq-relx/blob/8b6b49ad94b2f4dee7478e9a10d064a2c5f468ce/bin/emqttd_ctl#L71

Should we change the command 'cut -d = -f 2' to 'cut -d = -f 2-' ?
Like follows:
COOKIE=`egrep '^[ \t]*node.cookie[ \t]*=[ \t]*' $RUNNER_ETC_DIR/emq.conf 2> /dev/null | tail -1 | cut -d = -f 2-`

**Comment by emqplus** [comment]
Close the issue.
