### ISSUE TITLE
Mac OSX sierra - after making project, mqtt connection crashes server

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emq-relx#153]
Every time trying connect via an MQTT client,  Server responds with error, disconnecting the client.

Running on:
Version 2.3.1 - Mac OSX sierra 10.12.6 (Erlang/OTP 19 [erts-8.3])

Error:
`
gen_server <0.1453.0> terminated with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142

2017-12-07 13:27:21.251 [error] <0.1390.0> Supervisor 'esockd_connection_sup - <0.1390.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1463.0> exit with reason no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in context connection_crashed
`

**Comment by emqplus** [comment]
@syberkitten Please build from the master branch. The issue is duplicated with https://github.com/emqtt/emqttd/issues/1389

**Comment by syberkitten** [comment]
@emqplus Thanks, What is main difference between the emq-relx 
and the master branch (https://github.com/emqtt/emqttd) ?

**Comment by terry-xiaoyu** [comment]
@syberkitten emq-relx is for building OTP releases for all of the EMQ server-side projects, including the emqttd and the plugins. 
If you want to use mqtt broker, you only need to clone the emq-relx project and make. All the emq broker related projects (including the emqtt) will be fetched and built automatically.

For more details, see [Erlang.mk](https://erlang.mk/guide/relx.html)

**Comment by emqplus** [comment]
@syberkitten Fixed the issue in 2.3.2
