### ISSUE TITLE
Make fails due to undefined macro 'SN_RC_MQTT_FAILURE'

### ISSUE THREAD

**Issue by Zagrophyte** [emqtt/emq-relx#154]
REF: https://github.com/emqtt/emq-sn/issues/58 

Build on ARM Debian failing with following issue from emq_sn:

```
make[1]: Entering directory '/home/pi/emq-relx/deps/emq_sn'
 DEPEND emq_sn.d
 ERLC   emq_sn_app.erl emq_sn_asleep_timer.erl emq_sn_broadcast.erl emq_sn_config.erl emq_sn_gateway.erl emq_sn_gateway_sup.erl emq_sn_message.erl emq_sn_normal_topics.erl emq_sn_predefined_topics.erl emq_sn_sup.erl emq_sn_topic_manager.erl
src/emq_sn_gateway.erl:592: undefined macro 'SN_RC_MQTT_FAILURE'
src/emq_sn_gateway.erl:810: function transform/2 undefined
src/emq_sn_gateway.erl:598: Warning: function send_publish/8 is unused
../../erlang.mk:1174: recipe for target 'ebin/emq_sn.app' failed
make[2]: *** [ebin/emq_sn.app] Error 1
../../erlang.mk:992: recipe for target 'app' failed
make[1]: *** [app] Error 2
make[1]: Leaving directory '/home/pi/emq-relx/deps/emq_sn'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2
```

**Comment by sanyaade-iot** [comment]
Hi 
Just had the same issue on Ubuntu Server 16.04  with erlang/otp version is: 20

> sn_predefined_topics.erl emq_sn_sup.erl emq_sn_topic_manager.erl
src/emq_sn_gateway.erl:592: undefined macro 'SN_RC_MQTT_FAILURE'
src/emq_sn_gateway.erl:810: function transform/2 undefined
src/emq_sn_gateway.erl:106: Warning: gen_fsm:start_link/3 is deprecated and will be removed in a future release; use gen_statem:start_link/3
src/emq_sn_gateway.erl:110: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
src/emq_sn_gateway.erl:113: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
src/emq_sn_gateway.erl:598: Warning: function send_publish/8 is unused
../../erlang.mk:1174: recipe for target 'ebin/emq_sn.app' failed
make[2]: *** [ebin/emq_sn.app] Error 1
../../erlang.mk:992: recipe for target 'app' failed
make[1]: *** [app] Error 2
make[1]: Leaving directory '/var/www/html/site30/emq-relx/deps/emq_sn'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2

Any help/solution/pointer --much appreciated!

God blesses!!!

Best regards,
Sanyaade

**Comment by emqplus** [comment]
@sanyaade-iot @Zagrophyte Fixed in PR: https://github.com/emqtt/emq-sn/pull/59

**Comment by sanyaade-iot** [comment]
Okay I got it fix but I can't remember how I did since its almost few days ago. I have to edit a file move port address: 80 -->81 and port: 8080 --> 8083 plus couple of un-comment from the configuration file

God blesses!!!

Best regards,
Sanyaade
