### ISSUE TITLE
Start emqtt at boot on raspberry pi

### ISSUE THREAD

**Issue by hictao** [emqtt/emq-relx#164]
I successfully built Emqtt on raspberry pi 3 model b using these series of commands

```
sudo apt-get update

sudo apt-get install erlang-dev erlang-edoc erlang-eunit erlang-reltool erlang-crypto erlang-eldap erlang-public-key erlang-runtime-tools erlang-ssl
sudo apt-get install wget libssl-dev ncurses-dev
wget http://www.erlang.org/download/otp_src_18.3.tar.gz
tar -xzvf otp_src_19.3.tar.gz
cd otp_src_18.3/
./configure
make
sudo make install

git clone https://github.com/emqtt/emq-relx.git
cd emq-relx && make
cd _rel/emqttd && ./bin/emqttd console
```
and the emqtt works as expected with console and start.

But I couldn't make it start at boot. I tried this script [https://github.com/emqtt/emq-package/blob/master/deb/debian/init.script](https://github.com/emqtt/emq-package/blob/master/deb/debian/init.script) 
with these changes :

```
NAME=emqttd
DAEMON=/opt/emqttd/bin/$NAME
SCRIPTNAME=/etc/init.d/$NAME
```

but it doesn't work

Errors:
In the first place it said that the emqtt user not found then I added that user and set it as owner of the opt/emqttd folder.
now the status is : 

emqttd.service - LSB: Erlang MQTT Broker
   Loaded: loaded (/etc/init.d/emqttd)
   Active: failed (Result: exit-code) since Thu 2018-01-04 11:28:08 WET; 51s ago
  Process: 538 ExecStart=/etc/init.d/emqttd start (code=exited, status=1/FAILURE)

Jan 04 11:28:08 rpi-expactiv_06 systemd[1]: emqttd.service: control process exited, code=exited status=1
Jan 04 11:28:08 rpi-expactiv_06 systemd[1]: Failed to start LSB: Erlang MQTT Broker.
Jan 04 11:28:08 rpi-expactiv_06 systemd[1]: Unit emqttd.service entered failed state.
pi@rpi-expactiv_06:~ $ nano /etc/init.d/emqttd

Is there something I'am missing ?

**Comment by Zagrophyte** [comment]
Is your built release still in _rel? It looks like you're mixing init.d and systemd scripts, as well as referring to paths where your binaries don't exist.

I had success with systemd, here's what I did:

1. Build emq-relx (looks like you've done this already)
2. Copy the emqttd folder that's in _rel to `/home/pi/emqttd`
3. I made a systemd service file called emqttd.service that looks like the following (**substitute root with whatever user/group you have created for this purpose**):
```[Service]
WorkingDirectory=/home/pi/emqttd
ExecStart=/home/pi/emqttd/bin/emqttd start
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=emqttd
User=root
Group=root
Type=forking
[Install]
WantedBy=multi-user.target
```
4. Copy to systemd system folder `sudo cp emqttd.service /etc/systemd/system/emqttd.service`
5. Enable the service: `sudo systemctl enable emqttd`
6. Reload the daemon: `sudo systemctl daemon-reload` (do this anytime you edit the service file!)
7. Try to start: `sudo systemctl start emqttd`
8. If any errors occurred, check for errors: `journalctl -xe`

I *think* I got all the steps I took above, let me know if I missed anything.

**Comment by turtleDeng** [comment]
@hictao Please use package branch compile

**Comment by hictao** [comment]
Thank you @Zagrophyte and @turtleDeng for your help.
I followed @Zagrophyte guide and it worked for me, here is my final service file content:
```
[Unit]
Description=EMQTTD mqtt broker
After=network.target

[Service]
WorkingDirectory=/home/pi/emqttd
ExecStart=/home/pi/emqttd/bin/emqttd start
ExecStop=/home/pi/emqttd/bin/emqttd stop
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=emqttd
User=root
Group=root
Type=forking
[Install]
WantedBy=multi-user.target
```
