### ISSUE TITLE
build error on amazon aws ec2

### ISSUE THREAD

**Issue by jianglinchun** [emqtt/emq-relx#17]
DEPEND esockd.d
 ERLC   esockd.erl esockd_acceptor.erl esockd_acceptor_sup.erl esockd_access.erl esockd_app.erl esockd_cidr.erl esockd_connection.erl esockd_connection_sup.erl esockd_gen.erl esockd_keepalive.erl esockd_listener.erl esockd_listener_sup.erl esockd_net.erl esockd_ratelimit.erl esockd_server.erl esockd_sup.erl esockd_transport.erl esockd_udp.erl
src/esockd_cidr.erl:59: syntax error before: 
src/esockd_cidr.erl:63: syntax error before: 
src/esockd_cidr.erl:54: function parse_addr/1 undefined
src/esockd_cidr.erl:55: function parse_cidr/3 undefined
src/esockd_cidr.erl:128: Warning: function start_mask/2 is unused
src/esockd_cidr.erl:136: Warning: function end_mask/2 is unused
src/esockd_cidr.erl:158: Warning: function bmask/2 is unused
src/esockd_cidr.erl:163: Warning: function calc_end_address/2 is unused
src/esockd_cidr.erl:166: Warning: function bor_with_mask/2 is unused
src/esockd_cidr.erl:171: Warning: function band_with_mask/2 is unused
src/esockd_cidr.erl:176: Warning: function bit_count/1 is unused
make[2]: *** [ebin/esockd.app] Error 1
make[1]: *** [app] Error 2
make[1]: Leaving directory `/root/emqttd-2.0.6/deps/esockd'
make: *** [deps] Error 2

**Comment by jianglinchun** [comment]
http://emqtt.io/downloads/latest/centos7 works on amzon AWS

**Comment by jhaoheng** [comment]
Hello, today i build emq 2.0.7 in aws centos7 instance

1. git clone https://github.com/emqtt/emq-relx
2. cd emq-relx && make
3. ./bin/emqttd start

hope it would help

**Comment by emqplus** [comment]
closed the issue.
