### ISSUE TITLE
Can not add new lib

### ISSUE THREAD

**Issue by solomonwzs** [emqtt/emq-relx#191]
Hi.

I write a plugin and it depend on eredis_cluster, but when I create the release, eredis_cluster didn't appear in _rel/emqttd/lib/

> make[1]: Leaving directory '/home/solomon/workspace/erlang/emq-relx/deps/emq_auth_jwt'
> make[1]: Entering directory '/home/solomon/workspace/erlang/emq-relx/deps/emq_rf'
> make[2]: Entering directory '/home/solomon/workspace/erlang/emq-relx/deps/eredis_cluster'
> make[2]: Leaving directory '/home/solomon/workspace/erlang/emq-relx/deps/eredis_cluster'
>  DEPEND emq_rf.d
>  ERLC   emq_rf.erl emq_rf_acl.erl emq_rf_app.erl emq_rf_auth.erl emq_rf_client.erl emq_rf_http.erl emq_rf_http_api.erl emq_rf_http_auth.erl emq_rf_message.erl emq_rf_redis.erl emq_rf_session.erl emq_rf_sup.erl
>  APP    emq_rf.app.src
> make[1]: Leaving directory '/home/solomon/workspace/erlang/emq-relx/deps/emq_rf'
> ===> Starting relx build process ...
> ===> Resolving OTP Applications from directories:
>           /home/solomon/workspace/erlang/emq-relx/deps
>           /usr/lib/erlang/lib
>           /home/solomon/workspace/erlang/emq-relx/apps
>           /home/solomon/workspace/erlang/emq-relx/_rel
> ===> Resolved emqttd-2.3.6
> ===> Including Erts from /usr/lib/erlang
> ===> release successfully created!

> -> % ls _rel/emqttd/lib/
> asn1-5.0.5                    eldap-1.2.3              emq_auth_username-2.3.6    emq_rf-1            gen_logger-1.2      luerl-0.3       public_key-1.5.2
> bcrypt-git                    emq_auth_clientid-2.3.6  emq_coap-2.3.6             emq_sn-2.3.6        goldrush-0.1.9      mnesia-4.15.3   recon-2.3.2
> bson-v0.2.2                   emq_auth_http-2.3.6      emq_dashboard-2.3.6        emq_stomp-2.3.6     gproc-git           mochiweb-4.2.1  runtime_tools-1.12.5
> clique-git                    emq_auth_jwt-2.3.6       emq_lua_hook-2.3.6         emqttd-2.3.6        inets-6.5           mongodb-3.0.0   sasl-3.1.1
> compiler-7.1.5                emq_auth_ldap-2.3.6      emq_modules-2.3.6          emq_web_hook-2.3.6  jsx-2.9.0           mysql-1.3.1     ssl-8.2.5
> crypto-4.2.1                  emq_auth_mongo-2.3.6     emq_plugin_template-2.3.6  epgsql-3.4.1        jwerl-0.2.0         observer-2.7    stdlib-3.4.5
> cuttlefish-2.0.10-7-g26989cf  emq_auth_mysql-2.3.6     emq_recon-2.3.6            eredis-1.1.0        kernel-5.4.3        os_mon-2.4.4    syntax_tools-2.1.4
> ecpool-0.2                    emq_auth_pgsql-2.3.6     emq_reloader-2.3.6         esockd-5.2          lager-3.2.2         pbkdf2-2.0.1    syslog-1.0.5
> ekka-0.2.2                    emq_auth_redis-2.3.6     emq_retainer-2.3.6         gen_coap-0.2.0      lager_syslog-3.0.1  poolboy-1.5.1   xmerl-1.3.16

Is there something I'am missing ?

**Comment by terry-xiaoyu** [comment]
hi, 

Add your plugin follow this guide:
http://emqtt.io/docs/v2/plugins.html#plugin-development-guide

And don't forget to add your application in the relx.config:

e.g.
```
{eredis_cluster, load}
```
