### ISSUE TITLE
App built on Windows 7 doesn't work

### ISSUE THREAD

**Issue by ChikamaYan** [emqtt/emq-relx#202]
### Environment: 
Windows 7
emq-relx-2.3.10
Msys2
Erlang/OTP 21.0
### Issue
After building on Msys2, when I tried to run _./_rel/emqttd/bin/emqttd console_, I got following errors:

> =CRASH REPORT==== 4-Jul-2018::16:33:16.352000 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.125.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.113.0>]
    message_queue_len: 0
    messages: []
    links: [<0.116.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 234
  neighbours:

> =CRASH REPORT==== 4-Jul-2018::16:33:18.333000 ===
  crasher:
    initial call: esockd_listener:init/1
    pid: <0.367.0>
    registered_name: []
    exception error: bad argument
      in function  apply/3
         called as apply({gen_logger,error_logger_logger,2},error,[])
      in call from esockd_listener:init/1 (src/esockd_listener.erl, line 97)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.364.0>,esockd_sup,<0.145.0>]
    message_queue_len: 0
    messages: []
    links: [<0.364.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1164
  neighbours:
16:33:18.366 [error] Autocluster exception: {badmatch,{error,{{'EXIT',{{badmatch,{error,{{badarg,[{erlang,apply,[{gen_logger,error_logger_logger,2},error,[]],[]},{esockd_listener,init,1,[{file,"src/esockd_listener.erl"},{line,97}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{child,undefined,listener,{esockd_listener,start_link,['mqtt:tcp',{{0,0,0,0},1883},[{connopts,[]},{sockopts,[{send_timeout_close,true},{send_timeout,15000},binary,{packet,raw},{reuseaddr,true},{backlog,1024},{nodelay,true}]},{acceptors,16},{max_clients,102400},{access,[{allow,all}]}],<0.366.0>,{gen_logger,error_logger_logger,2}]},transient,4294967295,worker,[esockd_listener]}}}},[{esockd_listener_sup,start_link,4,[{file,"src/esockd_listener_sup.erl"},{line,62}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,671}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,420}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{child,undefined,{listener_sup,{'mqtt:tcp',{{0,0,0,0},1883}}},{esockd_listener_sup,start_link,['mqtt:tcp',{{0,0,0,0},1883},[{connopts,[]},{sockopts,[{send_timeout_close,true},{send_timeout,15000},binary,{packet,raw},{reuseaddr,true},{backlog,1024},{nodelay,true}]},{acceptors,16},{max_clients,102400},{access,[{allow,all}]}],{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,0.75}]]}]},transient,infinity,supervisor,[esockd_listener_sup]}}}}

Which causes most of the functions to not work.

What have I done wrong, or it's a problem with relx 2.3.10?

**Comment by Gilbert-Wong** [comment]
Sorry , emq-relx 2.3.10 doesn't support run on Erlang/OTP 21. You need to downgrade your Erlang version.

We have schedule to adapt to latest Erlang version. It will be released as emq-relx 3.0
