### ISSUE TITLE
编译出错，mac, erlang 0TA21

### ISSUE THREAD

**Issue by JasperLai** [emqtt/emq-relx#207]
sed "s/{{EXTRA_OPTS}}/ {d,namespaced_types},/" Emakefile.src > Emakefile
erl -noinput -eval 'up_to_date = make:all()' -s erlang halt
 GEN    rebar.config
 GEN    rebar.config
 ERLC   emq_coap_app.erl emq_coap_config.erl emq_coap_mqtt_adapter.erl emq_coap_ps_resource.erl emq_coap_ps_topics.erl emq_coap_registry.erl emq_coap_resource.erl emq_coap_server.erl emq_coap_sup.erl emq_coap_timer.erl
src/emq_coap_ps_resource.erl:241: field location_path undefined in record coap_content
src/emq_coap_ps_resource.erl:260: field location_path undefined in record coap_content
src/emq_coap_ps_resource.erl:19: Warning: undefined callback function coap_get/4 (behaviour 'coap_resource')
src/emq_coap_ps_resource.erl:19: Warning: undefined callback function coap_observe/4 (behaviour 'coap_resource')
src/emq_coap_ps_resource.erl:240: Warning: variable 'LocPath' is unused
src/emq_coap_ps_resource.erl:273: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
make[2]: *** [ebin/emq_coap.app] Error 1
make[1]: *** [app] Error 2

**Comment by Gilbert-Wong** [comment]
Please use English to open issue, the master branch of  emq-relx does not support erlang otp 21 . The new emq-relx which adapted to erlang otp 21 is developing now. Wait for a few days, please.
