### ISSUE TITLE
load plugin emq_dashboard wrong

### ISSUE THREAD

**Issue by Xwiam** [emqtt/emq-relx#209]
[error] [error] Failed to start connection on 0.0.0.0:18083 - {'EXIT',{undef,[{mochiweb_http,start_link,[{esockd_connection,[#Port<0.2509>,#Fun<esockd_transport.2.122912610>,[]]},{emq_dashboard,handle_request,[{state,"/home/qjzh/emq-relx/_rel/emqttd/lib/emq_dashboard-2.3.11/priv/www",#Fun<emq_dashboard.1.119262490>}]}],[]},{esockd_connection_sup,handle_call,3,[{file,"src/esockd_connection_sup.erl"},{line,146}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}

what's wrong when emq load emq_dashboard?

**Comment by Gilbert-Wong** [comment]
Is there any another processes occuping port 18083 ?

**Comment by Xwiam** [comment]
emqttd 2.3.11 is running now
Eshell V9.3  (abort with ^G)
(emq@127.0.0.1)1> Load emq_mod_presence module successfully.
dashboard:http listen on 0.0.0.0:18083 with 4 acceptors.

emq can start successfully.but when I request 18083,it doesn't work,as the log above presented.
@Gilbert-Wong

**Comment by Xwiam** [comment]
This is the log screenshot.It seemly shows nothing different.

![_20180808140008](https://user-images.githubusercontent.com/20536143/43819084-1560beaa-9b14-11e8-9701-5ed855013822.png)
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Of course there is some thing different. What is the process called `ibm-mqisdp`?

**Comment by Xwiam** [comment]
The log shows that the **ibm-mqisdp** process is listening port 1883,but I don't know why it shows _ibm-mqisdp_.

![_20180808154311](https://user-images.githubusercontent.com/20536143/43823507-cc6c6218-9b21-11e8-8823-9dee45e45712.png)

@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
So `ibm-mqisdp` occupy the port 1883 and it triggers abnormal actions of emqttd.

**Comment by Xwiam** [comment]
I agree with you.How can I find out the abnormal cause? 
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Try to kill the process which occupies the port emqttd needs and restart emqttd.

**Comment by Xwiam** [comment]
The process PID is 16189.Should i killed it? I have tried restart  emqttd many times.But it still doesn't work.

**Comment by Gilbert-Wong** [comment]
If the process is useless to you, killed it. If it is useful, read the emq documentation and modify the default ports  emqttd have to use.

**Comment by Xwiam** [comment]
The process is listening port 18083,1883,8080,8083,8084,11883,8883.If I kill it,how does it work? Maybe I get it wrong.Please make it clear, thank you.
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Kill all other processes unrelated with emqttd which occupies the port emqttd needs and restart emqttd.

**Comment by Xwiam** [comment]
(1) I download the source code from https://github.com/emqtt/emq-relx.git and make.It doesn't work.
(2)If i download the binary code from https://github.com/emqtt/emqttd.git. It work well. 
(3)And I remove the plugin emq_dashboard from the deps directory and reload it. It still dosen't work.
(4)Should I remove all the plugins and reload all?Are there some plugins the dashborad rely on?

@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Sorry, I don't understand what you mean. Why it doesn't work when you make emq-relx ? Did it make failed?

**Comment by Xwiam** [comment]
I'm sorry.The source code can make success.What I mean is the dashboard plugin dosen't work.

**Comment by Gilbert-Wong** [comment]
Which otp version do you use? Which platform do you run emqttd and give me more detailed information. There is no problem when I run emqttd on debian, mac os x , centos, etc.

**Comment by Xwiam** [comment]
This is the relx.config file.I add some plugins,these plugins work well.But I don't know if these plugins will influence the dashboard plugin.  
@Gilbert-Wong 
This is the centos version.
![_20180811102609](https://user-images.githubusercontent.com/20536143/43987278-08320146-9d51-11e8-8d14-309d984e3f9d.png)

This is the relx.config
{release, {emqttd, "2.3.11"}, [
  kernel,
  sasl,
  crypto,
  public_key,
  asn1,
  syntax_tools,
  ssl,
  xmerl,
  os_mon,
  inets,
  goldrush,
  compiler,
  runtime_tools,
  {observer, load},
  %%{wx, load},
  pbkdf2,
  bcrypt,
  lager,
  luerl,
  syslog,
  gen_logger,
  gproc,
  esockd,
  cuttlefish,
  jsx,
  **### kafkamocker,
  ###ekaf,**
  {gen_coap, load},
  mochiweb,
  {mnesia, load},
  {ekka, load},
  emqttd,
  {emq_sn, load},
  {emq_coap, load},
  {emq_recon, load},
  {emq_stomp, load},
  {emq_modules, load},
  {emq_retainer, load},
  {emq_reloader, load},
  {emq_dashboard, load},
  {emq_web_hook, load},
  {emq_lua_hook, load},
  %%{emq_elixir_plugin, load},
  {emq_auth_clientid, load},
  {emq_auth_username, load},
  {emq_auth_ldap, load},
  {emq_auth_http, load},
  {emq_auth_mongo, load},
  {emq_auth_mysql, load},
  {emq_auth_pgsql, load},
  {emq_auth_redis, load},
  {emq_auth_jwt, load},
  {emq_plugin_template, load},
  **###{emq_plugin_wunaozai, load}**
]}.

{include_src, false}.

{extended_start_script, false}.

{generate_start_script, false}.

{sys_config, false}.

{vm_args, false}.

{overlay_vars, "vars.config"}.

{overlay, [
    {mkdir, "etc/"},
    {mkdir, "log/"},
    {mkdir, "data/"},
    {mkdir, "data/mnesia"},
    {mkdir, "data/configs"},
    {mkdir, "hook_lua"},
    {template, "bin/emqenv", "bin/emqenv"},
    {template, "bin/emqttd", "bin/emqttd"},
    {template, "bin/emqttd_ctl", "bin/emqttd_ctl"},
    {template, "bin/emqttd.cmd", "bin/emqttd.cmd"},
    {template, "bin/emqttd_ctl.cmd", "bin/emqttd_ctl.cmd"},
    {copy, "rel/conf/plugins", "etc/"},
    {copy, "deps/emqttd/etc/certs", "etc/"},
    {template, "rel/conf/emq.conf", "etc/emq.conf"},
    {template, "rel/conf/ssl_dist.conf", "etc/ssl_dist.conf"},
    {template, "rel/conf/plugins/emq_coap.conf", "etc/plugins/emq_coap.conf"},
    {copy, "rel/conf/acl.conf", "etc/acl.conf"},
    {copy, "data/loaded_plugins", "data/loaded_plugins"},
    {copy, "bin/cuttlefish", "bin/cuttlefish"},
    {copy, "bin/nodetool", "bin/nodetool"},
    {copy, "rel/schema", "releases/\{\{rel_vsn\}\}/"},
    {copy, "bin/install_upgrade_escript", "bin/install_upgrade_escript"}
]}.

**Comment by Gilbert-Wong** [comment]
It is unnecessary to add these plugins.  I recommend you to add issue from this [template](https://github.com/emqtt/emqttd/blob/master/.github/ISSUE_TEMPLATE.md). It makes your issue more clear.

I notice that 3 days ago you said you 

> remove the plugin emq_dashboard from the deps directory

You thought that emq_dashboard cause the problem so you want to remove this dependency from emq-relx?  I do not recommend you to do like this because emq_dashboard is an important component of emqttd.

**Comment by Xwiam** [comment]
Sorry,I download emq-relx from https://github.com/emqtt/emq-relx.git,so it is better to add issue here ,I think.Here are three questions:
(1)I remove the emq_dashboard from the deps and reload it from https://github.com/emqtt/emq-dashboard.git.
(2)I just want to know why it doesn't work.If I remove the plugin,will it influence the use of emqttd?
(3)If i reload it from https://github.com/emqtt/emq-dashboard.git,will it work well?

And I will add issue from that template as you  say.Thank you very much.
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Of course it will influence the use of emqttd ! Why did you need to remove the emq_dashboard from the deps ? The emq-dashboard include erlang code. You need to remake the emq-relx first, then restart emqttd.

**Comment by Xwiam** [comment]
Sorry,I don't know erlang very well.I will reload the emq-relx and remake it.Thank you.

@Gilbert-Wong
