### ISSUE TITLE
unable to execute 'emqttd console' - crashing with "cannot get bootfile,no_dot_erlang.boot"

### ISSUE THREAD

**Issue by imsbhatnagar** [emqtt/emq-relx#211]
#### Environment

- OS: CentOS 6.8
- Erlang/OTP:  21
- EMQ: 2.3.11

#### Description
emq compiled successfully from the source code and erl/opt proper versions installed on CentOS 6.8.
Same issue is seen when executing on Mac 10.12.6

./bin/emqttd console
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done

emqttd (master) $ erl
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Please suggest

**Comment by terry-xiaoyu** [comment]
Hi, OTP 21 is not supported by EMQ 2.x. EMQ 3.0 running on OTP21 is coming soon.
