### ISSUE TITLE
build error:  rebar: Command not found

### ISSUE THREAD

**Issue by wumao** [emqtt/emq-relx#213]
#### Environment

- OS:  ubuntu 
Max@gitlab:~/emq-relx$ uname -a
Linux gitlab 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Max@gitlab:~/emq-relx$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

- Erlang/OTP:  
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

- EMQ:  
git clone https://github.com/emqtt/emq-relx.git

#### Description

*A description of the issue*
Max@gitlab:~/emq-relx$ make

make[1]: Entering directory '/home/Max/emq-relx/deps/goldrush'
make[1]: rebar: Command not found
Makefile:13: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
make[1]: Leaving directory '/home/Max/emq-relx/deps/goldrush'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by Gilbert-Wong** [comment]
Checkout V2.3.11 tag and use erlang/otp 20 as erlang runtime. The problem could be solved.

**Comment by wumao** [comment]
thank you.
