### ISSUE TITLE
emqtt 2.3.11:   ./emqttd console    error: 

### ISSUE THREAD

**Issue by wumao** [emqtt/emq-relx#214]
#### Environment

- OS:  unbuntu 16.04
- Erlang/OTP:  21
- EMQ:  2.3.11

#### Description

*A description of the issue*

Max@gitlab:~/emq-relx-2.3.11/_rel/emqttd/bin$ ./emqttd console
erlexec: Error 13 executing '/home/Max/emq-relx-2.3.11/_rel/emqttd/erts-10.0/bin/beam.smp'.

**Comment by Gilbert-Wong** [comment]
I remembered I told you  use erlang 20 to build this project. First you need to execute "make distclean" to clean the beam file which compiled with erlang 21. Next, make again. Then ./_rel/emqttd/bin/emqttd console to launch emq
On Aug 30, 2018, 10:51 AM +0800, 绿米-毛勇 <notifications@github.com>, wrote:
Environment

  *   OS: unbuntu 16.04
  *   Erlang/OTP: 21
  *   EMQ: 2.3.11

Description

A description of the issue

Max@gitlab:~/emq-relx-2.3.11/_rel/emqttd/bin$ ./emqttd console
erlexec: Error 13 executing '/home/Max/emq-relx-2.3.11/_rel/emqttd/erts-10.0/bin/beam.smp'.

**Comment by wumao** [comment]
Sorry, it may be caused by environmental problems. I can compile successfully with another computer. Thank you.  you can close this.
