### ISSUE TITLE
Complile failure, Dependency emq_mod_retainer

### ISSUE THREAD

**Issue by vidhill** [emqtt/emq-relx#24]
I am building release v2.0.7 using docker, 

The emq-relx Make recipe has started to fail, with the error:
` Dependency emq_mod_retainer is specified as a dependency but is not reachable by the system.`

I see a in a recent commit https://github.com/emqtt/emq-retainer/commit/1e3063a591e11dcfb3ee267507c28b94886dce6c that emq_mod_retainer project has been renamed to emq_retainer 

Would this be causing the build to fail, is there any way to work around this? (without waiting on a release)

**Comment by vidhill** [comment]
I have a workaround,
By cloning `emq_mod_retainer` directly into the `deps/emq_mod_retainer` folder

```Bash
git clone -b 'v2.0.7' https://github.com/emqtt/emq-relx.git /emq-relx
git clone -b 'v2.0.7' https://github.com/emqtt/emq-retainer.git /emq-relx/deps/emq_mod_retainer
```

I'm sure there's probably a better solution..

**Comment by vidhill** [comment]
It appears @emqplus has created a new repo for emq-mod-retainer https://github.com/emqtt/emq-mod-retainer/releases a few days ago.
I will check with my project tomorrow but I believe this will fix this issue..

**Comment by emqplus** [comment]
@vidhill duplicated with #25

**Comment by vidhill** [comment]
All good now, 
fixed in https://github.com/emqtt/emq-relx/issues/25
