### ISSUE TITLE
Dependency Error, building v2.0.7

### ISSUE THREAD

**Issue by vidhill** [emqtt/emq-relx#25]
I am building release v2.0.7 using docker,

I am getting a runtime error, 
``` bash
[error] Lager failed to install handler {lager_syslog_backend,{"emq",local0}} into lager_event, retrying later : {error, {"no such file or directory", "syslog.app"}}
```

Looking at the [Makefile for tag v2.0.7](https://github.com/emqtt/emqttd/blob/v2.0.7/Makefile) `lager` is a dependency, 
Comparing to 2.1, it appears that lager_syslog has been added as a dependency for 2.1

How could a dependency that wasn't in 2.0.7 be working it's way into my build?

**Comment by vidhill** [comment]
Have I an incorrect expectation, should I expect to still to be able to build v2.0.7 using the following

```
RUN git clone -b 'v2.0.7' https://github.com/emqtt/emq-relx.git /emq-relx \ 
RUN cd /emq-relx && make \
```

**Comment by emqplus** [comment]
@vidhill Sorry for the dependency mess. I tagged to 'v2.0.7p1' to resolve this issue:
```
RUN git clone -b 'v2.0.7p1' https://github.com/emqtt/emq-relx.git /emq-relx  
RUN cd /emq-relx && make
```

**Comment by vidhill** [comment]
Tested and all is building and working correctly now, 
Many thanks
