### ISSUE TITLE
Binary crashes after building on Mac OS v10.12.3

### ISSUE THREAD

**Issue by fabianTMC** [emqtt/emq-relx#26]
I am building on Mac OS v10.12.3 with Erlang v19. I had a few issues while building initially since the rel/ folder was not present. I fixed that by using the configuration from the downloadable mac os version  and after that all the build issues disappeared. 

After building, when I try to run the binary, this is what I get:
> $ ./_rel/emqttd/bin/emqttd foreground
!!!!
!!!! WARNING: ulimit -n is 256; 1024 is the recommended minimum.
!!!!
Exec: /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/erts-8.2/bin/erlexec -noshell -noinput +Bd -boot /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/releases/2.1/emqttd -mode embedded -boot_var ERTS_LIB_DIR /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/erts-8.2/../lib -mnesia dir "/Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/data/mnesia/emqttd@127.0.0.1" -config /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/data/configs/app.2017.02.22.12.20.54.config -args_file /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/data/configs/vm.2017.02.22.12.20.54.args -vm_args /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd/data/configs/vm.2017.02.22.12.20.54.args -- foreground
Root: /Users/fabian/dev/sorted/playground/emq-relx/_rel/emqttd
starting emqttd on node 'emqttd@127.0.0.1'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
12:21:00.838 [error] CRASH REPORT Process <0.996.0> with 0 neighbours exited with reason: no match of right hand value undefined in emqttd_plugins:plugin/1 line 116 in application_master:init/4 line 134
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,undefined},[{emqttd_plugins,plugin,1,[{file,\"src/emqttd_plugins.erl\"},{line,116}]},{emqttd_plugins,'-list/0-lc$^0/1-0-',1,[{file,\"src/emqttd_plugins.erl\"},{line,102}]},{emqttd_plugins,'-list/0-lc$^0/1-0-',1,[{file,\"src/emqttd_plugins.erl\"},{line,102}]},{emqttd_plugins,list,0,[{file,\"src/emqttd_plugins.erl\"},{line,102}]},{emqttd_plugins,load_plugins,2,[{file,\"src/emqttd_plugins.erl\"},{line,74}]},{emqttd_app,start,2,[{file,\"src/emqttd_app.erl\"},{line,48}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,undefined},[{emqttd_plugins,plugin,1,[{file,"src/emqttd
Crash dump is being written to: log/crash.dump...done

Any help would be much appreciated :

**Comment by edsonhuang** [comment]
please provide your emq directory under the/etc/plugins configuration files thanks

**Comment by fabianTMC** [comment]
etc/plugins directory 
https://drive.google.com/drive/folders/0Bz0fT_1TJXQPdGZCNmJvX01zeGc

lib/ directory
https://drive.google.com/drive/folders/0Bz0fT_1TJXQPSnNrTW9iYjBobmM

I've also uploaded the entire directory here in case you need something else https://drive.google.com/drive/folders/0Bz0fT_1TJXQPc2xoWkpZZTJEcms

**Comment by turtleDeng** [comment]
@fabianTMC 
```
RUN rm -rf deps _rel rel
make
```

**Comment by fabianTMC** [comment]
It works now. I don't understand what was going wrong? When I had compiled it after a fresh clone, it was throwing a vm.args issue similar to this https://github.com/emqtt/emqttd/issues/866

I tried a fresh clone as well and there are no issues any more.

**Comment by fabianTMC** [comment]
Update: Now when I try to build, I get the following error:

> ./rebar skip_deps=true escriptize
==> cuttlefish (escriptize)
 DEPEND gproc.d
 ERLC   gproc.erl gproc_app.erl gproc_bcast.erl gproc_dist.erl gproc_info.erl gproc_init.erl gproc_lib.erl gproc_monitor.erl
gproc_pool.erl gproc_ps.erl gproc_pt.erl gproc_sup.erl
src/gproc_dist.erl:23: Warning: behaviour gen_leader undefined
 APP    gproc.app.src
make[3]: rebar: No such file or directory
make[3]: *** [deps] Error 1
make[2]: *** [deps] Error 2
make[1]: *** [deps] Error 2
make: *** [deps] Error 2

**Comment by emqplus** [comment]
@fabianTMC please install a rebar, and put it under the /usr/local/bin/

**Comment by fabianTMC** [comment]
It works now. Thanks :)
