### ISSUE TITLE
Compile error in v2.1.0-beta.2

### ISSUE THREAD

**Issue by watchworld** [emqtt/emq-relx#32]
in goldrush error info: rebar command not found
copy rebar to goldrush folder,modify makefile @REABAR to ./rebar
the question is ok

**Comment by emqplus** [comment]
@watchworld Please install `rebar` and put in /user/local/bin folder.

On Ubuntu: sudo apt-get install rebar

**Comment by emqplus** [comment]
Fixed in PR: https://github.com/emqtt/emq-relx/pull/33
