### ISSUE TITLE
spell error

### ISSUE THREAD

**Issue by congleetea** [emqtt/emq-relx#38]
https://github.com/emqtt/emq-relx/blob/master/vars.config#L17 : 
{runner_bin_dir,     "$RUNNER_ROOT_DIR/bin/"} should be {runner_bin_dir,     "$RUNNER_ROOT_DIR/bin"}.    
the last "/" is needless， otherwise, 
https://github.com/emqtt/emq-relx/blob/master/bin/emqttd#L124 and https://github.com/emqtt/emq-relx/blob/master/bin/emqttd#L266 will be wrong.

**Comment by emqplus** [comment]
@congleetea Thanks for your review. Removed the '/' suffix now.
