### ISSUE TITLE
Dependency bcrypt is specified as a dependency but is not reachable by the system.

### ISSUE THREAD

**Issue by edmandiesamonte** [emqtt/emq-relx#64]
I keep getting this message when building emq-relx on Ubuntu 16.04 LTS with Erlang OTP 19.

Anything I'm missing?

**Comment by huangdan** [comment]
hi @edmandiesamonte ,You can clean and try to get the dependenies again:
```
1.cd emq-relx
2.rm -rf deps/* && make
```
